# Generated by Django 3.2.12 on 2023-01-15 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 12, 27, 29, 955441), null=True, verbose_name='date published'),
        ),
    ]
